### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by towardshch** [hukkelas/full_body_anonymization#1]
excuse, dockerfile can't links to your file

**Comment by hukkelas** [comment]
Sorry, it is now added [here](Dockerfile).

You can build it with the following:
```
docker build -t full_body_anonymization --build-arg WANDB_API_KEY=YOUR_WANDB_API_KEY \
    --build-arg UID=$(id -u) --build-arg UNAME=$(id -un) 
```
Note that WANDB_API_KEY is not required unless you'd like to log with wandb.

**Comment by towardshch** [comment]
thanks!
